- week4/week4.js
1. 직업군별 점수를 저장할 score 객체를 생성합니다.
2. table 배열의 각 element를 split(' ')해서 접근하기 쉽게 만들고, split된 각 element(이하 column이라고 함)의 0번째 원소가 직업군의 이름이므로 score에 모든 직업군의 점수를 0으로 저장합니다. 
3. languages 배열을 순회하면서 table을 순회합니다. 각 column에서 언어의 점수를 탐색합니다. 점수가 있다면 선호도 점수와 곱해서 score에 업데이트합니다.
4. score 객체의 values 중 최댓값을 뽑습니다.
5. socre 객체의 keys를 순회하며 최댓값과 같은 값을 가진 key를 ans 배열에 저장합니다.
6. ans의 원소 개수가 1이 넘는다면 사전순으로 정렬 후 0번째 원소를 반환합니다.
> [김예임][4주차] 직업군 추천하기

- week5/solution.js
https://programmers.co.kr/learn/courses/30/lessons/84512?language=javascript
> [김홍중][5주차] 모음 사전

- .idea/.gitignore
- .idea/misc.xml
- .idea/modules.xml
- .idea/vcs.xml
- Algorithm/6주차/복서 정렬하기.js
win 배열 : 이긴 횟수 
winFromMoreWeight 배열 : 자신보다 무거운 사람을 이긴 횟수
lose 배열 : 진 횟수
head2head를 순회하며 위에 해당하는 배열에 값을 처리
memObj는 해당 배열들을 객체 형태로 묶어서 표현
이를 순서에 따라 정렬 시킨 후 해당하는 idx만을 반환
> [김형욱][6주차] 복서 정렬하기복서 정렬하기 코드 추가

- week6/solution.js
calculateWinRate 함수에서 forEach를 두 번쓰기 싫어서 reduce로 시도해보았는데 오히려 더 이해하기는 어려운 코드가 된것 같기도합니다.
> [김홍중][6주차] 복서 정렬하기

- week6/week6.js
1. 복서의 [승률, 무거운 사람 이긴 횟수, 몸무게, 번호] 배열을 만드는 함수 boxerInfo를 선언합니다.
- 경기 횟수, 승리 횟수, 무거운 사람 이긴 횟수를 저장할 변수를 선언합니다.
- 전적 string을 순회하며 N이 아닌 경우 경기 횟수를 하나 더합니다.
- W인 경우 승리 횟수를 하나 더하고, 상대와 몸무게를 비교해 상대가 무거운 경우 winHeavierCnt를 하나 더합니다.
- matchCnt가 0인 경우 승률 계산했을 때 오류가 발생해서 미리 처리해줍니다.
2. 복서 정보에 따라 정렬하는 함수를 선언합니다.
- 승률 > 무거운 사람 이긴 횟수 > 몸무게 > 번호 순으로 비교하고 정렬합니다.
- 번호는 오름차순, 나머지는 내림차순으로 정렬합니다.
3. head2head에 위의 함수를 순서대로 적용한 후 번호를 추출합니다.
> [김예임][6주차] 복서 정렬하기

- week7/solution.js
room이라는 새로운 배열에 입실 퇴실을 반복하는 과정에서 answer를 계산하는것의 아이디어를 생각했지만 테스트를 통과하지는 못했습니다!
leave를 기준으로 leave에 해당하는것이 room에 있을때까지 room에 추가하고 추가할때 answer 계산을 처리합니다. (이 부분이 필요한지 헷갈립니다. 아이디어 생각할때는 없던 단계인데 코드 짜다보니 들어올때마다 추가하게 되었습니다)
아니라면 answer계산을 처리하고 해당하는것을 room에서 뺍니다.(같이 있는 경우를 생각하고자 room의 길이 -1로 자신 외의 경우의 수를 계산합니다.)
> [김홍중][7주차] 입실 퇴실

- Algorithm/7주차/입실퇴실.js
관련 내용은 해당 링크를 읽어주시면 감사하겠습니다. 
[링크](https://velog.io/@khw970421/%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%A8%B8%EC%8A%A4-%EC%9E%85%EC%8B%A4-%ED%87%B4%EC%8B%A4-%EC%9C%84%ED%81%B4%EB%A6%AC-%EC%B1%8C%EB%A6%B0%EC%A7%80-7%EC%A3%BC%EC%B0%A8)
> [김형욱][7주차] 입실 퇴실 

- week8/solution.js
- week8/solution2.js
최소 직사각형을 해결합니다.
[리팩토링 과정](https://hongjungkim-dev.tistory.com/883)
> [김홍중][8주차] 최소직사각형, 로또의 최고 순위와 최저 순위

- week9/solution.js
> [9주차][김홍중] 전력망을 둘로 나누기

- week13/solution.js
순열을 이용하였고
순열은 다음을 참고하였습니다.
[링크](https://jun-choi-4928.medium.com/javascript%EB%A1%9C-%EC%88%9C%EC%97%B4%EA%B3%BC-%EC%A1%B0%ED%95%A9-%EC%95%8C%EA%B3%A0%EB%A6%AC%EC%A6%98-%EA%B5%AC%ED%98%84%ED%95%98%EA%B8%B0-21df4b536349)
> [13주차][김홍중] 피로도

- week14/solution.js
시작점은 모든 P
'O'를 만나면 탐색
'P'를 만나면 맨허튼 거리를 판단하여 성공, 실패 (이때 성공은 모든 P에 대하여 성공)
P에서 시작하여 'X'가 아닌 지점을 방문하는것으로 생각하여 BFS방식으로 시도하였습니다.
하지만 오류를 해결하지 못하여 아직 미해결 코드입니다.
> [14주차][김홍중] 거리두기

- Algorithm/14주차/거리두기 확인하기.js
[문제설명](https://velog.io/@khw970421/%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%A8%B8%EC%8A%A4-%EA%B1%B0%EB%A6%AC%EB%91%90%EA%B8%B0)
> [14주차][김형욱] 거리두기

- week15/solution.js
* 조합
* 이진탐색
을 이용하여 풀이
효율성이 어려워서 다른 코드 참고하여 공부하였습니다
https://velog.io/@alvin/%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%A8%B8%EC%8A%A4-%EB%AC%B8%EC%A0%9C%ED%92%80%EC%9D%B4-%EC%88%9C%EC%9C%84-%EA%B2%80%EC%83%89-Javascript
> [15주차][김홍중] 순위검색

- algorithm/행렬_테두리_회전하기.js
> 01/12 문제 풀이

- Algorithm/4주차(시즌2)/예상대진표.js
> [3주차][김형욱] 예상대진표

- algorithm/쿼드압축_후_개수_세기.js
recursion을 활용하여 구현하였습니다.
traverse중에 다른 숫자가 나올경우, 구역으로 4으로 쪼개어 각 4구역에 대한 traverse를 진행합니다.
모두 같은 숫자인 구역인 경우, 해당 숫자 갯수를 1 증가합니다.
> [2주차][김정운] 쿼드압축 후 개수 세기

- algorithm/배달.js
> [2주차][김정운] 배달

- algorithm/게임_맵_최단거리.js
> [3주차][김정운] 게임 맵 최단거리

- algorithm/이진_변환_반복하기.js
s 가 '1' 로 변환할때까지 반복문을 진행한다.
split 과 filter 메소드를 활용하여 0을 삭제한후,
toString(2) 을 통해 이진 문자열로 변환한다.
문제에서 요구되는 값을 카운트하여 반환한다.
> [5주차][김정운] 이진 변환 반복하기

- algorithm/주차_요금_계산.js
두개의 해시맵을 활용하였다.
입고된 차량의 시각정보를 기록하는 historyMap,
주차장에 머문 시간정보를 기록하는 timeSpentMap
마지막 출차 기록이없는 차량은 23:59분에 출고한 것으로 간주하기때문에,
입고와 출고 절차를 진행한후 historyMap에 남아있는 정보들에 대해서 23:59분 출고한것으로 처리를 진행한다.
이후 timeSpentMap을 차량번호 오름차순으로 정렬후, 요금을 계산한다.
> [5주차][김정운] 주차 요금 계산

- season2/week1/solution.js
회전하면서 값 바꾸기가 미완성 상태입니다.
- 테두리 구하기
row가 양 끝일때만 다 담고,
else col에 해당하는 것을 담고 비어있는것은 0으로 배열에 담기
- 최소 구하기
테두리를 구해서 나온 배열의 최소 구하기
- 회전하면서 값 바꾸기
loop를 돌면서 최소를 먼저 구하고 이후에 회전하면서 값 바꾸기를 진행하고자 하였습니다. 왜냐하면 값 바꾸기전에 최소를 구해도 되기때문에 마지막에는 회전하면서 바꿀 필요는 없다고 생각하였습니다. 
자식에서 부모로 올라가서 tree와 깊이우선탐색(DFS)를 떠올렸습니다.
감을 못잡겠습니다.
> [1주차][김홍중] 행렬 테두리

- src/season2/week2/quad.js
> [2주차][김홍중] 쿼드압축 후 개수 세기

- season2/week3/deletePair.js
> [3주차][김홍중] 짝지어 제거하기

- season2/week4/snail.md
snail.md에 풀이방법 고민한 사항 정리와 동일한 내용
- 첫번째 고민한 로직
방향을 고려하여 구현하는것이 까다로울것이라고 예상하여 다른 방법을 고민하였다.
- 두번째 고민한 로직
수학적인 공식을 이용하는 로직을 생각하였다. 하지만 이렇게 짜는 경우 인덱스가 낮은것에서 높은순으로 순회하다가 다시 낮은순으로 순회하여야한다. 이러한 과정이 구현할때에 헷갈리고 복잡할 수 있다고 생각하였다.
- 세번째 고민한 로직
러시아 인형처럼 삼각형이 안에 계속 들어있다는 아이디어로 시작하였다.
안쪽 삼각형까지 1번만 고려하여 값을 저장하고 그 다음 2번, 3번 막대기를 순차적으로 처리하여 저장순서에 문제가 없도록 한다. 이렇게 하려면 1, 2, 3번 막대기의 시작 숫자를 수학 공식으로 구하는것을 고민하였다.
> [4주차][김홍중] 삼각 달팽이
